config/routes.rb
Rails.application.routes.draw do

   resources :entries do
    collection do
      post :send_message
      post :sort
    end
   end

   resources :users
   resource :sessions

  root 'sessions#new'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :food
  validates_presence_of :date
  before_create :set_position_number

  scope :ordered, -> { order(:position) }

  def info_notice?
    calories.nil?
  end

  private

  def set_position_number
    self.position = maximum_position + 1
  end

  def maximum_position
    Entry.where(user_id: user_id, date: date).maximum(:position) || 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :entries, dependent: :delete_all
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  def entries_of_today
    entries.where(date: Date.today)
  end
end

app/models/user/calorie_calculator.rb
class User::CalorieCalculator
  def initialize(user, date)
    @user = user
    @date = date
  end

  def daily_calories
    sum_of_calories
  end

  def weekly_calories
    sum_of_weekly_calories.to_i
  end

  def weekly_progress
    [progress_in_week, 100].min
  end

  def ideal_progress
    [calculate_ideal_progress, 100].min
  end


  private

  attr_reader :user, :date

  def target_calories
    user.target_calories.to_f
  end

  def sum_of_calories
    daily_entries.sum(:calories)
  end

  def daily_entries
    user.entries.where(date: date)
  end

  def sum_of_weekly_calories
    user.entries.where(date: date.beginning_of_week..date).sum(:calories).to_f
  end

  def progress_in_week
    (sum_of_weekly_calories / (target_calories*7) * 100).round
  end

  def calculate_ideal_progress
    (((date.beginning_of_week..date).count * target_calories) / (target_calories*7) * 100).round
  end
end

app/models/user/missing_entries_reminder.rb
class User::MissingEntriesReminderJob
  def self.run
    User.where.not(slack_url: nil).each do |user|
      new(user).send_reminder
    end
  end

  def initialize(user)
    @user = user
  end

  def send_reminder
    return if entries_today?
    send_slack_reminder
  end


  private

  def send_slack_reminder
    if Rails.env.production?
      Slack::Notifier.new(@user.slack_url).ping("Bitte kcal eintragen!")
    else
      puts "[SLACK] Sending Reminder to #{@user.name}..."
    end
  end

  def entries_today?
    return unless @user.entries[Date.today] != nil
  end
end

app/models/user/missing_entries_reminder_job.rb
class User::MissingEntriesReminderJob
  def self.run
    User.where.not(slack_url: nil).each do |user|
      new(user).send_reminder
    end
  end

  def initialize(user)
    @user = user
  end

  def send_reminder
    return false if entries_today?
    send_slack_reminder
    true
  end


  private

  def send_slack_reminder
    if Rails.env.production?
      Slack::Notifier.new(@user.slack_url).ping("Bitte kcal eintragen! #{href="http://awesomecalories.herokuapp.com/"}")
    else
      puts "[SLACK] Sending Reminder to #{@user.name}..."
      puts "Bitte kcal eintragen! #{href="http://awesomecalories.herokuapp.com/"}"
    end
  end

  def entries_today?
    @user.entries.where(date: Date.today).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :ensure_logged_in
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  private

  def ensure_logged_in
    return if logged_in?
    redirect_to new_sessions_path, notice: "Einloggen!"
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    return unless session[:user_id].present?
    @current_user  ||= User.find(session[:user_id])
  end

end

app/controllers/entries_controller.rb
require 'slack-notifier'

class EntriesController < ApplicationController

  def index
    @date = date
    @entry = Entry.new(date: @date)
    @entries = current_user.entries.where(date: @date).ordered
  end

  def create
    @entry = current_user.entries.build(entry_params)
    respond_to do |format|
      if @entry.save
        #format.html { redirect_to entries_path(date: @entry.date) }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        @entries = current_user.entries.where(date: @entry.date)
        @date = date
        #format.html { render :index }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entry = current_user.entries.find(params[:id])
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_path(date: @entry.date) }
    end
  end

  def send_message
    notifier = Slack::Notifier.new(current_user.slack_url)
    notifier.ping "Bitte kcal eintragen!"
    redirect_to entries_path
  end

  def sort
    Entry.transaction do
      # entry_ids => [13, 12, 7, 17]
      params[:entry_ids].each_with_index do |entry_id, i|
        entry = current_user.entries.find(entry_id)
        entry.position = i + 1
        entry.save!
      end
    end
    head :ok
  end


  private

  def entry_params
    params.require(:entry).permit(:food, :calories, :date, :position)
  end

  def date
    params[:date].try(:to_date) || Date.current
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_logged_in, only: [:new, :create]

  def new
    if logged_in?
      redirect_to entries_path
    end
  end

  def create
    user = User.where(email: session_params[:email]).first
    if user.present? && user.password == session_params[:password]
      session[:user_id] = user.id
      redirect_to entries_path
    else
      redirect_to new_sessions_path, :flash => { :error => "Email und Passwort stimmen nicht überein" }
    end
  end

  def destroy
    session.clear
    redirect_to new_sessions_path
  end

  def session_params
    params.permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_logged_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to entries_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to entries_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def remaining_calories
    total = current_user.target_calories
    @entries.each do |entry|
      total -= entry.calories
    end
    return total
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :target_calories, :slack_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def calories_class(entry)
    if entry.calories < 0
      'green'
    else
      'pink'
    end
  end

  def bar_class(weekly_calories, ideal_calories)
    if weekly_calories < ideal_calories
      'progress-bar-success'
    else
      'progress-bar-danger'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_entry.html.haml
%tr.crosshair{id: entry.id}
  %td.food= entry.food
  %td.calories{class: calories_class(entry)}= entry.calories
  %td.action
    = link_to entry_path(entry), :method => :delete, data: { confirm: 'Are you sure?' } do
      %span.glyphicon.glyphicon-trash.trash.grey{:'aria-hidden' => "true"}
      %br

app/views/entries/_form.html.haml
= form_for(@entry, remote: true) do |f|
  =f.text_field :date, hidden: true
  %table.entries
    %thead
      %tr
        %td.food=f.text_field :food, :autofocus=> true, :placeholder => "Food", class: 'form-control food'
        %td.calories=f.text_field :calories, :placeholder => "kcal", class: 'form-control calories'
        %td.submit=f.submit "ok", class: 'submit-button btn btn-default light-green-button'

app/views/entries/_notice.html.haml
%tr.crosshair{id: entry.id}
  %td(colspan=2)
    .separator
      %span=entry.food
    %td.action
      = link_to entry_path(entry), :method => :delete, data: { confirm: 'Are you sure?' } do
        %span.glyphicon.glyphicon-trash.trash.grey{:'aria-hidden' => "true"}
        %br

app/views/entries/edit.html.haml
%h1= "Editing Entry"
= render 'form'
= link_to 'Show', @entry
= link_to 'Back', entries_path

app/views/entries/index.html.haml
- content_for(:title, 'Health Challenge')
%div.navbar
  %ul.nav.nav-tabs
    - (@date.beginning_of_week..@date.end_of_week).each do |date|
      %li{:role => "presentation", class: (date == @date ? 'active' : '')}
        = link_to entries_path(date: date), class: 'text-center green' do
          = l(date, format: :dayname_abbreviation)
          %br
          - if User::CalorieCalculator.new(current_user, date).daily_calories >= current_user.target_calories
            %strong.pink= User::CalorieCalculator.new(current_user, date).daily_calories
          - else
            %strong.green= User::CalorieCalculator.new(current_user, date).daily_calories
=render('form')
%table.entries.real-table
  %tbody#sortable
    - @entries.each do |entry|
      - if entry.info_notice?
        =render 'notice', entry: entry
      - else
        =render 'entry', entry: entry

%table.entries
  %tr
    %td(colspan=2)
      %hr
  %tr
    %td.total.space= "Total"
    %td.calories.total-calories.space
      - if User::CalorieCalculator.new(current_user, @date).daily_calories > current_user.target_calories
        %strong.pink= User::CalorieCalculator.new(current_user, @date).daily_calories
      - else
        %strong.green= User::CalorieCalculator.new(current_user, @date).daily_calories
    %td

.progress
  .progress-bar{:role => "progressbar", :style => "width: #{User::CalorieCalculator.new(current_user, @date).weekly_progress}%", class: bar_class(User::CalorieCalculator.new(current_user, @date).weekly_progress, User::CalorieCalculator.new(current_user, @date).ideal_progress)}
  .display
    .weekly_calories.white=User::CalorieCalculator.new(current_user, @date).weekly_calories
    .ideal_calories.white=current_user.target_calories*7
  %div.marker{:style => "left: #{User::CalorieCalculator.new(current_user, @date).ideal_progress}%"}
%table.bar
  %tbody
    %tr
      %td.grey.left="Monday"
      %td.grey.right="Sunday"

= hidden_field_tag "display_calories", current_user.target_calories
= hidden_field_tag "weekly_calculation", User::CalorieCalculator.new(current_user, @date).weekly_calories

:coffee
  $ ->
    $('a.btn.btn-default.glyphicon.glyphicon-calendar').datepicker(todayHighlight: true, weekStart: 1).on 'changeDate', (e) ->
      day = e.date.getDate()
      month = e.date.getMonth() + 1
      year = e.date.getFullYear()
      window.location = "/entries?date=" + year + "-" + month + "-" + day

    $("#sortable").sortable
      items: "tr.crosshair"
      axis: "y"
      appendTo: document.body
      update: (e, ui) ->
        order = []
        $("#sortable tr.crosshair").each (item) ->
          order.push(parseInt($(this).attr('id')))
        $.post("/entries/sort", entry_ids: order)

app/views/entries/new.html.haml
%h1 New Entry

= render 'form'
%br
= link_to 'Back', entries_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    = favicon_link_tag 'favicon.ico'
    %title CalorieTracker
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,300,600", :rel => "stylesheet", :type => "text/css"}
      = javascript_include_tag 'application', 'data-turbolinks-track' => true
      = csrf_meta_tags
  %body
    - if logged_in?
      %nav.navbar.navbar-default.navbar-static-top
        .row
          .col-xs-6
            %a.btn.btn-default{:href => entries_path(date: Date.current), :role => "button"} Today
            %a.btn.btn-default.glyphicon.glyphicon-calendar
          .col-xs-6.text-right
            Signed in as #{current_user.name} –
            = link_to 'Logout', sessions_path, method: :delete
            = link_to edit_user_path(current_user) do
              %span.btn.btn-default.glyphicon.glyphicon-user
    .container
      %h1.white= yield(:title)

      = flash[:notice] if flash[:notice].present?

      .container-white
        = yield

app/views/users/_edit_form.html.haml
= form_for(@user) do |f|
  .field.form-group
    = f.label :email
    %br
    = f.text_field :email, :autofocus=> true
    %br
    = f.label :slack_url
    %br
    = f.text_field :slack_url
    %br
    = f.label :target_calories
    %br
    = f.text_field :target_calories
    %br
    %br
    = f.submit "Speichern", :id => ""

app/views/users/_form.html.haml
= form_for(@user) do |f|
  .field.form-group
    = f.label :name
    %br
    = f.text_field :name, :autofocus=> true
    %br
    = f.label :email
    %br
    = f.text_field :email
    %br
    = f.label :target_calories
    %br
    = f.text_field :target_calories
    %br
    = f.label :password
    %br
    = f.password_field :password
    %br
    %br
    = f.submit "Speichern", :id => ""

app/views/users/edit.html.haml
%h1= "Editing User"
= render 'edit_form'
= link_to 'Show', @user
= link_to 'Back', entries_path

app/views/users/index.html.haml
%h1 Users

%table
  %tbody
    - @users.each do |user|
      %tr
      %td
        = link_to user.name, user

app/views/users/new.html.haml
%h1 Registration

= render 'form'
%br
= link_to 'Back', users_path

app/views/users/show.html.haml
%h1 User

%table
  %tr
    %td= @user.name
    %td= @user.email

%br/
%br/

= link_to "Back", users_path